wallpaper {
    monitor = eDP-1
    path = /home/fox/.dot/wallpapers/1979-black-hole-simulation.jpg
}

wallpaper {
    monitor = DP-2
    path = /home/fox/.dot/wallpapers/1979-black-hole-simulation.jpg
}

wallpaper {
    monitor = PNP(LBT) Rokid Max Unknown
    path = /home/fox/.dot/wallpapers/1979-black-hole-simulation.jpg
}
